config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resource :profile, only: [ :show, :edit, :update ], controller: "users/profile"
  devise_for :users
  root "home#index"
  get "about", to: "pages#about", as: :about

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  namespace :admin do
    get "dashboard", to: "dashboard#index"
  end

  namespace :admin do
    resources :tickets, only: [ :index, :edit, :update, :destroy ] do
      resources :comments, only: [ :create ]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.erb
<!-- Home page, for page user is directed after login -->
<h1>Welcome to IT Helpdesk</h1>

<!-- If user is signed in, show link to their tickets -->
<% if user_signed_in? %>
  <%= link_to 'View My Tickets', tickets_path, class: 'btn btn-primary' %>
  <% else %>
    <p><%= link_to 'Login', new_user_session_path, class: 'btn' %></p> 
    <p><%= link_to "Register", new_user_registration_path, class: 'btn' %></p>
<% end %>

<!-- If user is admin, show link to admin panel to view all tickets -->
<% if user_signed_in? && current_user.admin? %>
  <p><%= link_to "View All Tickets", admin_tickets_path, class: 'btn btn-primary' %></p>
<% end %>
<br>
<br>
<br>
<p>Need help? Contact our support team at <a href="mailto:support@ithelpdesk.com">support@srcsolutions.com</a></p>