config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resource :profile, only: [ :show, :edit, :update ], controller: "users/profile"
  devise_for :users
  root "home#index"
  get "about", to: "pages#about", as: :about

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")

  namespace :admin do
    get "dashboard", to: "dashboard#index"
  end

  namespace :admin do
    resources :tickets, only: [ :index, :edit, :update, :destroy ] do
      resources :comments, only: [ :create ]
    end
  end
end

app/views/layouts/application.html.erb
<!-- Base format/layout HTML with Ruby embedded template for the application/all pages -->
<!DOCTYPE html>
<html>
  <head>
    <title>IT Helpdesk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
    <!-- renders a bar chart (category) using Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <body class="theme-orange">

    <header class="app-header">
      <!--h1 class="brand">IT Helpdesk</h1-->
      <%= image_tag 'logo_placeholder.png', class: 'logo-placeholder' %>
    </header>

    <!-- Navigation bar with conditional links based on user sign-in status and role -->
    <nav class="nav">
      <% if user_signed_in? %>           
        <%= link_to "Home", root_path %>
        <!--%= link_to "My Tickets", tickets_path % -->
        <%= link_to "Profile", profile_path %>
        <%= link_to "Settings", edit_user_registration_path %>
        <%= link_to "About Us", about_path %>
      <% end %>

      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Admin Dashboard", admin_dashboard_path %>
      <% end %>
    </nav>

    <nav class="nav1">
      <% if user_signed_in? %>              
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }%>
      <% end %>
    </nav>

    <!-- Main content area displaying flash messages and yielding to specific page content -->
    <main class="container">
      <% if notice %><p class="flash notice"><%= notice %></p><% end %>
      <% if alert %><p class="flash alert"><%= alert %></p><% end %>
      <%= yield %>
    </main>

    <br><br><br>

    <footer class="app-footer">
      <span>SRC Solutions @ 2025</span>
    </footer>
  </body>
</html>
